### ISSUE TITLE
Image classification as new fink_science module

### ISSUE THREAD

**Issue by FusRoman** [astrolabsoftware/fink-science#104]
A new fink_science module that perform a classification of image alerts based on their visual contents. 
A large part of the image contains only ponctual object due to large number of variable star but sometime, ZTF can observe a larger object like a galaxy, a nebula or other things. 
The purpose of this module is the detection of this kind of larger object and add this additionnal information to the fink custom alert schema.
Two major labels are assign to the alert, star for image which contains only ponctual object and extend for image which contains at least one extend object. 
Two additionnals labels is used to filter image that are noised and corrupted.

**Comment by JulienPeloton** [comment]
Done in #105
