### ISSUE TITLE
Unordered times in FINK data

### ISSUE THREAD

**Issue by VoidDruid** [astrolabsoftware/fink-science#190]
In some light curves dates are out of order. Example:

- _objectId_ - ZTF17aaaablp
- _jd_ - **2458899.6356597, 2458833.7344907, 2459487.8912384, 2459107.9318519,** ...

2nd is smaller than 1st, 4th is smaller than 3rd. Dataset - [from slack](https://fink-broker.slack.com/files/UHNLTKLGG/F03QLKBMHCY/lc_features_agglightcurve_unknownobject_hundredmeasmin.parquet).

**Comment by JulienPeloton** [comment]
Hi @VoidDruid -- thanks for the report. If I understand correctly this problem arises on a specific file, and not in Fink data in general?

**Comment by VoidDruid** [comment]
> Hi @VoidDruid -- thanks for the report. If I understand correctly this problem arises on a specific file, and not in Fink data in general?

I also encountered it when working with sample data given in science module tutorial.
