### ISSUE TITLE
[Elasticc] New version of cbpf_classifier (refered as cats) for finer classes

### ISSUE THREAD

**Issue by and-santos** [astrolabsoftware/fink-science#230]
Following the steps to open a pull request, I'm opening this issue to describe the CBPF Classifier to be merged on fink-science.

Our PR adds new fine class classifiers for broad predictions  from first CBPF_classifier (know named as CATS - CBPF Algorithm for Transient science)

Some remarks about our new hierarchical classifier:

The ouput know is a pandasDaframe with two columns: broad_preds and fine_preds.
The broad_preds have for each row a vector with probabilities for each broad class (from left to right: SN_like, fast, long, periodic, AGN).  and follows the fine_classifier map below:

```
fine_classifier_map = {
        0: sn_model, (Classification: SN-like)
        1: fast_model, (Classification: Fast)
        2: long_model, (Classification: Long)
        3: periodic_model, (Classification: Periodic)
        4: None (Classification: AGN, don't need a second classifier)
    }
```
if "null" or nan are shows in this vector, it means that the input data have only on point. 

Using the fine_classifier_map, the input data goes to the corresponding fine_classifier, which outputs another array with probabilities corresponding to each class. Each of the fine_classifiers also have it's own mapping:

```
    SN model:
        SN_map = {
            0: 'SNIa',
            1: 'SNIb/c',
            2: 'SNII',
            3: 'SNIax',
            4: 'SNIa-91bg'
        }
    Fast model:
        fast_model = {
            0: 'KN',
            1: 'M-dwarf-flare',
            2: 'dwarf novae',
            3: 'uLens'
        }
    Long model:
        long_model = {
            0: 'SLSN',
            1: 'TDE',
            2: 'ILOT',
            3: 'CART',
            4: 'PISN'
        }
    Periodic model:
        periodic_model = {
            0: 'Cepheid',
            1: 'RR Lyrae',
            2: 'Delta Scuti',
            3: 'EB'
        }
```

Talking specifically about the second ouput (from finer classifiers).
Some of them have intentional null outputs in order to all probabilities vector have the same shape. 
Sadly, I din't make it work a return with probability vectors with different shapes.

For example, the output of  SN_model classification (which contains 5 possible classifications) is something like 
```
[probability_1, probability_2, probability_3, probability_4, probability_5]
```
For fast/periodic classification:
[probability_1, probability_2, probability_3, probability_4, null]

for AGN:
```
[probability_1, null, null, null, null]
```
I did some tests locally, but I think it needs some more tests inside fink to confirm that everything is working.

Feel free to make any requests about changes on the code.

**Comment by JulienPeloton** [comment]
Done in #232
