### ISSUE TITLE
[ELAsTiCC] new earlySNIa model 

### ISSUE THREAD

**Issue by emilleishida** [astrolabsoftware/fink-science#311]
I will make a pool request with the modifications. 

there is a new function: get_sigmoid_features_elasticc_perfilter
which is the one to be used

**Comment by emilleishida** [comment]
I do not know how to ensure this, but after feature extraction, the order of the features in the final matrix (before going into the machine learning model) matters. 

The order should be:

columns_to_keep =  ['diaObjectId', 'alertId', 'classId', 'hostgal_dec', 'hostgal_ra', 'hostgal_snsep', 'hostgal_zphot', 'hostgal_zphot_err', 'mwebv_err','mwebv_err', 'ra', 'decl']  + followed by the sigmoid features in order

**Comment by JulienPeloton** [comment]
Thanks @emilleishida -- why do you include errors on `mwebv` (`mwebv_err`) but not its value?

**Comment by emilleishida** [comment]
>>  why do you include errors on extinction (mwebv_err) but not its value?

stupidity ... it was a typo that I only realized after the feature extraction was done ... I will fix it ..
