### ISSUE TITLE
SLSN and AGN ELAsTiCC models were not updated

### ISSUE THREAD

**Issue by erusseil** [astrolabsoftware/fink-science#351]
SLSN and AGN classifiers for ELAsTiCC were not updated with the latest AL model.
AGN model format should also be saved with joblib instead of pickle.

**Comment by JulienPeloton** [comment]
Hello @erusseil -- you mean that in `kernel.py`, I should replace

```diff
- CLASSIFIER_ELASTICC = curdir + "/data/models/AGN_elasticc_alerts.pkl"
+ CLASSIFIER_ELASTICC = curdir + "/data/models/AGN_elasticc_alerts.joblib"
```
(and same for slsn)?

Does that also mean that the `.pkl`  files can be deleted in the repo?
