### ISSUE TITLE
VSX should be updated or matched directly from CDS

### ISSUE THREAD

**Issue by karpov-sv** [astrolabsoftware/fink-science#365]
AAVSO VSX is constantly being updated (e.g.current one in Vizier is `Version 2023-12-11`), and our local one is way too old. So we need to either regularly pull updates for it from CDS (`2278125` rows now, should not be too stressful), or just directly match it the same way we do with e.g. Gaia, using CDS XMatch.

**Comment by JulienPeloton** [comment]
Fix in #366
