### ISSUE TITLE
[Performances] Overview of science module performances

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science#44]
As of version 0.3.2, each module has the following performance (tested on the cloud, with 51 cores, and 106,000 alerts as input):

![fink_science_perf](https://user-images.githubusercontent.com/20426972/84004075-4e641c80-a96b-11ea-979d-57b02491323d.png)

What is called LSST scale in the figure means 10,000 alerts / 30 seconds; so that's ~3 alerts/second on 100 CPU. A module that would output results at a rate of 3 alerts/second would take the whole 30 second window to complete (the time between two batches of alerts), hence delaying the processing.

Ideally, each module should output an order of magnitude more alerts, i.e. take much less than 10% of the total time granted given the resources (100 CPU is a lower bound in the number of available CPU - but we want to make sure we can run it even at this low scale). 

Action item: speed-up by factor 10 the AL & microlensing modules.

**Comment by marcol480** [comment]
To increase the perf of random forest on ZTF, I actually let the algorithm run on all the CPUs 
(all the different realisations of the random trees are independent processes so there is no harm in principle and in practice).  

This choice is done within scikit learn by simply including  an option "n_jobs=-1" in the classifer. 
All this is opaque to your code which only uses the results in the model. I try to attach 
[here](https://github.com/astrolabsoftware/fink-science/files/4813614/RandomForestResult_rising_curve_prototype.obj.zip)

 a model which uses this approach. 
Do you see any improvements in the perf ?

**Comment by JulienPeloton** [comment]
Thanks @marcol480! Why would I need a specific model for this? Can I just try the new `n_jobs=-1` option with previous models?

**Comment by marcol480** [comment]
Sorry for being unclear : I called a model the output file, .obj, but it's the same _model_ as before, same data, same algorithm -- Random Forest.
