### ISSUE TITLE
[Bug] anomaly detection models have wrong name

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science#461]
@Knispel2 The zip files in `data/model/anomaly_detection` have correct names (with `_{model}` in it), but once decompressed we always end up with the same names

```python
forest_g_AAD.onnx
forest_r_AAD.onnx
```

while the code supposes the model name in the filename:

```python
g_model_path_AAD = f"{tmp_path}/forest_g_AAD{model}.onnx"
r_model_path_AAD = f"{tmp_path}/forest_r_AAD{model}.onnx"
```

Todo: decompress files, rename each model, recompress folders, push.

**Comment by JulienPeloton** [comment]
The error was unfortunately not caught by the CI because I skipped anomaly tests on a (merged) branch (https://github.com/astrolabsoftware/fink-science/commit/4191e9403cf2189e0b22cc618b6afe224469a42c), and I forgot to restore it... My fault!

**Comment by JulienPeloton** [comment]
Fortunately, only the model `""` is used in production.

**Comment by Knispel2** [comment]
I'm sorry, I was too inattentive... Thanks a lot for fixing it!
