### ISSUE TITLE
[Intraday data points and gaps] difference between simulations and alerts

### ISSUE THREAD

**Issue by marcol480** [astrolabsoftware/fink-science#50]
1. There is a major difference looking at light curves from ZTF-type simulations and light curves coming from the ZTF alerts : the difference is the presence of intraday data points in the history.
This is somehow unexpected and requires modifications in the way data are managed. 

I propose a way to get around this : _groupby_ by date and then average on the pandas DataFrame. 

2. There is another issue, with removing non-consecutive data points. That is OK for  ZTF simulations which have one data point per day unless seasonal effects come in;  
however it is too drastic for ZTF alerts, where it is not uncommon to have gaps of a few days between two consecutive measurements.  Hence the algorithm as it is would
 discarded too many alerts and requires a modification

**Comment by JulienPeloton** [comment]
Done in #51
